openapi: '3.0.3'
info:
  title: Detail Pesanan Restfull API
  description: API Spec for Menu Item Restfull API
  version: '1.0'
servers:
  - url: https://localhost:3000/api
paths:
  /detailPesanans:
    post:
      summary: Menambah data Detail Pesanan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pesanan_id:
                  type: integer
                menu_item_id:
                  type: integer
                jumlah_item_pesanan:
                  type: integer
                harga_item_pesanan:
                  type: integer                  
              required:
                - pesanan_id
                - menu_item_id
                - jumlah_item_pesanan
                - harga_item_pesanan
      responses:
        '201':
          description: menu items
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: number
                  data:
                    type: object                                          
                    properties:
                      id:
                        type: number
                      pesanan:                                                
                        type: object
                        properties:
                          id:
                            type: number
                          user:
                            type: object
                            properties:                              
                              name:
                                type: string
                              email:
                                type: string
                              pengguna:
                                type: string
                              tanggal_buat_akun:
                                type: string
                                format: date
                          total_harga:
                            type: number
                          status: 
                            type: string
                          tanggal_pembuatan_pesanan:
                            type: string
                            format: date
                      menu_tems:
                        type: object
                        properties:
                          id:
                            type: number
                          name:
                            type: string
                          deskripsi:
                            type: string
                          harga:
                            type: number
                          tanggal_penambahan_item_menu:
                            type: string
                            format: date
                      jumlah_item_pesanan:
                        type: number
                      harga_item:
                        type: number
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    get:
      summary: menampilkan data semua data menu items
      description: menampilkan tanpa menggunkan paginate

      responses:
        '200':
          description: menu items reading
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                  
                  data: 
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        pesanan:                                                
                          type: object
                          properties:
                            id:
                              type: number
                            user:
                              type: object
                              properties:                              
                                name:
                                  type: string
                                email:
                                  type: string
                                pengguna:
                                  type: string
                                tanggal_buat_akun:
                                  type: string
                                  format: date
                            total_harga:
                              type: number
                            status: 
                              type: string
                            tanggal_pembuatan_pesanan:
                              type: string
                              format: date
                        menu_tems:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                            deskripsi:
                              type: string
                            harga:
                              type: number
                            tanggal_penambahan_item_menu:
                              type: string
                              format: date
                        jumlah_item_pesanan:
                          type: number
                        harga_item:
                          type: number
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
  /detailPesanans/{id}:  
    get:
      summary: menampilkan data detail pesanan berdasarkan id
      parameters:
        - name: id
          in: path
          required: true
          description: detail pesanan id yang akan diambil
          schema:
            type: number
          
      responses:
        '200':
          description: detail pesanan reading
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                 
                  data: 
                    type: object
                    properties:
                        id:
                          type: number
                        pesanan:                                                
                          type: object
                          properties:
                            id:
                              type: number
                            user:
                              type: object
                              properties:                              
                                name:
                                  type: string
                                email:
                                  type: string
                                pengguna:
                                  type: string
                                tanggal_buat_akun:
                                  type: string
                                  format: date
                            total_harga:
                              type: number
                            status: 
                              type: string
                            tanggal_pembuatan_pesanan:
                              type: string
                              format: date
                        menu_tems:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                            deskripsi:
                              type: string
                            harga:
                              type: number
                            tanggal_penambahan_item_menu:
                              type: string
                              format: date
                        jumlah_item_pesanan:
                          type: number
                        harga_item:
                          type: number
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    put:
      summary: merubah data detail pesanan
      parameters:
        - name: id
          required: true
          in: path
          description: detail pesanan id yang akan diambil
          schema:
           type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pesanan_id:
                  type: integer
                menu_item_id:
                  type: integer
                jumlah_item_pesanan:
                  type: integer
                harga_item_pesanan:
                  type: integer
      responses:
        '201':
          description: data detail pesanan berhasil dirubah
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                  
                  data:
                    type: object                    
                    properties:
                        id:
                          type: number
                        pesanan:                                                
                          type: object
                          properties:
                            id:
                              type: number
                            user:
                              type: object
                              properties:                              
                                name:
                                  type: string
                                email:
                                  type: string
                                pengguna:
                                  type: string
                                tanggal_buat_akun:
                                  type: string
                                  format: date
                            total_harga:
                              type: number
                            status: 
                              type: string
                            tanggal_pembuatan_pesanan:
                              type: string
                              format: date
                        menu_tems:
                          type: object
                          properties:
                            id:
                              type: number
                            name:
                              type: string
                            deskripsi:
                              type: string
                            harga:
                              type: number
                            tanggal_penambahan_item_menu:
                              type: string
                              format: date
                        jumlah_item_pesanan:
                          type: number
                        harga_item:
                          type: number
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    delete:
      summary: menghapus data detail pesanan
      parameters:
        - name: id
          in: path
          required: true
          description: detail pesanan id yang akan diambil
          schema:
            type: number
      responses:
        '200':
          description: "data berhasil dihapus"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                 