openapi: '3.0.3'
info:
  title: Pesanan Restfull API
  description: API Spec for Category Restfull API
  version: '1.0'
servers:
  - url: https://localhost:3000/api
paths:
  /pesanans:
    post:
      summary: Menambah data pesanan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                total_harga:
                  type: integer
                status:
                  type: string
                tanggal_pembuatan_pesanan:
                  type: string
                  format: date
              required:
                - user_id
                - total_harga
                - status
                - tanggal_pembuatan_pesanan
      responses:
        '201':
          description: pesanan
          content:
            application/json:
              schema:
                type: object
                properties:
                  code: 
                    type: number
                  data:
                    type: object                                          
                    properties:
                      id:
                        type: number
                      user_id:
                        type: integer
                      total_harga:
                        type: integer
                      status:
                        type: string
                      tanggal_pembuatan_pesanan:
                        type: string
                        format: date
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    get:
      summary: menampilkan data semua data pesanan
      description: menampilkan tanpa menggunkan paginate

      responses:
        '200':
          description: pesanan reading
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                  
                  data: 
                    type: array
                    items:
                      type: object
                      properties:
                          id:
                            type: integer
                          user_id:
                            type: integer
                          total_harga:
                            type: integer
                          status:
                            type: string
                          tanggal_pembuatan_pesanan:
                            type: string
                            format: date
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
  /pesanan/{id}:  
    get:
      summary: menampilkan data pesanan berdasarkan id
      parameters:
        - name: id
          in: path
          required: true
          description: pesanan id yang akan diambil
          schema:
            type: number
          
      responses:
        '200':
          description: pesanan reading
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                 
                  data: 
                    type: object
                    properties:
                      id:
                        type: integer
                      user_id:
                        type: integer
                      total_harga:
                        type: integer
                      status:
                        type: string
                      tanggal_pembuatan_pesanan:
                        type: string
                        format: date
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    put:
      summary: merubah data pesanan
      parameters:
        - name: id
          required: true
          in: path
          description: pesanan id yang akan diambil
          schema:
           type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                 type: integer
                user_id:
                  type: integer
                total_harga:
                  type: integer
                status:
                  type: string
                tanggal_pembuatan_pesanan:
                  type: string
                  format: date
      responses:
        '201':
          description: data category berhasil dirubah
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                  
                  data:
                    type: object                    
                    properties:         
                      id:
                        type: integer             
                      user_id:
                        type: integer
                      total_harga:
                        type: integer
                      status:
                        type: string
                      tanggal_pembuatan_pesanan:
                        type: string
                        format: date
                  link:
                    type: array
                    items:
                      type: object
                      properties:
                        rel:
                          type: string
                        href:
                          type: string
    delete:
      summary: menghapus data pesanan
      parameters:
        - name: id
          in: path
          required: true
          description: pesanan id yang akan diambil
          schema:
            type: number
      responses:
        '200':
          description: "data berhasil dihapus"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number                 